### ISSUE TITLE
You can inject raw JS

### ISSUE THREAD

**Issue by zuzak** [matthojo/AskMatt#1]
Such as, for example, `<script>window.location = "http://google.com"</script>`.

**Comment by matthojo** [comment]
Cheers, I presume you just tested that ;) I'm fixing it right now. Thank you for the heads up.

**Comment by matthojo** [comment]
Should now be fixed in https://github.com/matthojo/AskMatt/commit/3d23c161b21c2cbdc781954ea7b6cf9e828ac825.
